### ISSUE TITLE
Internal page routing is not configured correctly

### ISSUE THREAD

**Issue by progzone122** [shomykohai/moto-penangf#3]
Routing similar links (which are not in the sidebar) to internal resources does not work correctly.
It seems that this needs to be configured, for example, as in the same React, Vue, etc.
![Screenshot_20241222-102811.png](https://github.com/user-attachments/assets/49950573-0c76-4141-b426-1744e07dbdca)

![Screenshot_20241222-102555~2.png](https://github.com/user-attachments/assets/e0ed38aa-d58d-4ad5-8b65-62702352d66c)

![Screenshot_20241222-102538.png](https://github.com/user-attachments/assets/216ff977-a8e0-4a91-809f-bf45d45d1013)

**Comment by shomykohai** [comment]
Weird,
I'm using docsify to make things easy, and on in local env the redirects works well.

I'll look this up right now.

Also, I'm gonna add you as a repo collaborator so it's easier to add more stuff that's missing if I miss the PRs (I don't get the notifications for this repo for some reason even if they're enabled)

**Comment by shomykohai** [comment]
It looks like docsify always starts the research of the file from the projects root, so to access a file in the dev directory from the dev directory again, we have to do

```[Testpoints](dev/testpoints.md)```

**Comment by shomykohai** [comment]
Fixed it, now relative paths are used instead (as it should have been from the start):


```md
# from bootloader.md in dev/

[Testpoints](testpoints.md) 


# from testpoints in dev/

[Bootloader](bootloader.md)
```

**Comment by progzone122** [comment]
![Screenshot_20241222-111933.png](https://github.com/user-attachments/assets/9314ecd4-c6ff-4be7-a76e-b595dd1fb1eb)

Now almost all the links from the sidebar are broken :(

**Comment by progzone122** [comment]
Wttfff
![Screenshot_20241222-112103~2.png](https://github.com/user-attachments/assets/8b4d2ac3-3940-4338-8668-f4546d994142)

**Comment by shomykohai** [comment]
I noticed lol, looks like relatives links impact the sidebar too, even tho it lives in the root

**Comment by shomykohai** [comment]
I'll have to make a different sidebar for every directory, or even better: find a way to make the sidebar ignore relative links

**Comment by shomykohai** [comment]
Seem to be an issue from docsify itself:
- docsifyjs/docsify#1891

I'll make different sidebars for every directory so that we can still use relative paths

**Comment by shomykohai** [comment]
@progzone122 does it work now?
I tried using absolute paths instead of relative paths in the sidebar, and it works for me!

**Comment by progzone122** [comment]
sidebar fixed
https://github.com/shomykohai/moto-penangf/commit/e81f8e6205d2c61d6172da2ad4bd46da36aeb0d0
